name: Code Review with AWS CodeGuru

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Trigger CodeGuru Reviewer
        run: |
          aws codeguru-reviewer create-code-review \
            --name "PR-${{ github.event.pull_request.number }}" \
            --repository-association-arn arn:aws:codeguru-reviewer:us-east-1:699298357726:association:c5d24b9a-19aa-4e4b-8e14-7f4abc62cadb \
            --type RepositoryAnalysis


      - name: Wait for Code Review Results
        run: |
          aws codeguru-reviewer list-code-reviews --provider-type GitHub --status Completed
