name: Code Review with Amazon Q Developer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Amazon Q Developer
        uses: amazon/q-dev-action@latest
        with:
          repo-url: ${{ github.repository }}
          pull-request-id: ${{ github.event.pull_request.number }}
          output-file: review_suggestions.json

      - name: Post Review Comments
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const suggestions = JSON.parse(fs.readFileSync('review_suggestions.json', 'utf-8'));
            const pullRequestNumber = context.payload.pull_request.number;

            for (const suggestion of suggestions.comments) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pullRequestNumber,
                body: suggestion.text
              });
            }
